In [2]:
import numpy as np

In [18]:
data = np.loadtxt("/Users/erikahartai/ttda/GALIBOS TUNELES MADRID.csv", 
                  delimiter=";", 
                  usecols = 1, 
                  skiprows=1, 
                  converters={1: lambda s:float(str(s).replace(",","."))},
                  encoding="latin-1")
print(data)
print(data.shape)


[2.95 4.   4.   4.   4.   4.   3.9  3.5  3.5  3.5  4.3  4.5  3.   3.
 2.95 4.   4.5  3.   4.   3.   4.   3.   3.   4.   3.   2.95 4.   4.
 4.   3.   2.95 2.85 2.85 3.   3.   3.   2.85 3.   3.   3.   3.   3.
 3.   2.85 4.   4.   3.   2.4  4.   4.   4.   4.3  3.5  2.7  2.95 2.95
 2.95 2.95 1.95 2.4 ]
(60,)


In [19]:
data = np.random.uniform(0.01,20.0,size=100000)
print(data[:5])

[ 1.41886693  8.83856505  1.00080203 17.5370623   7.68858501]


In [23]:
f = open("/Users/erikahartai/ttda/tmp.npy","wb") # Writing file, in Binary mode
np.save(f,data)
f.close()

with open("/Users/erikahartai/ttda/tmp2.csv","w") as f2: # Writing but in txt
    for n in data:
        f2.write(str(n)+",")

In [26]:
!ls -lih data/tmp*

zsh:1: no matches found: data/tmp*


In [29]:
data = np.random.uniform(0.01,20.0,size=100000)
data2 = np.random.normal(0.3,10,100000)
print(data[:5])
print(data2[:5])

f = open("/Users/erikahartai/ttda/tmp.npy","wb") # Writing file, in Binary mode
np.save(f,data)
np.save(f,data2)
f.close()

print("saved")


with open('/Users/erikahartai/ttda/tmp.npy', 'rb') as f:
    a = np.load(f)
    b = np.load(f)

print(a[:5])
print(b[:5])


[ 6.33663801  4.82919827 15.8940753   5.98327828 16.03521875]
[14.31985516  4.25595659 -4.59941403 -2.86951711 -4.00881155]
saved
[ 6.33663801  4.82919827 15.8940753   5.98327828 16.03521875]
[14.31985516  4.25595659 -4.59941403 -2.86951711 -4.00881155]


In [30]:
import pickle

with open("/Users/erikahartai/ttda/tmp3.npy",'wb') as f:
    pickle.dump(a, f)
    pickle.dump(b, f)

In [31]:
!ls -lih data/tmp*

zsh:1: no matches found: data/tmp*


In [32]:
f = "/Users/erikahartai/ttda//tmp3.npy"
ca = pickle.load(open(f,"rb"))
print(ca)
cb = pickle.load(open(f,"rb"))
print(cb)


[ 6.33663801  4.82919827 15.8940753  ... 13.80845347  7.46662072
  8.0226896 ]
[ 6.33663801  4.82919827 15.8940753  ... 13.80845347  7.46662072
  8.0226896 ]


In [ ]:
#Operaciones con series numpy

In [33]:
import numpy as np
a = np.array([.0,0.1])
b = np.array([1,1])
print(a+b)
print(a-b)
print(a/b)
print(a*b)
print(2**a)

[1.  1.1]
[-1.  -0.9]
[0.  0.1]
[0.  0.1]
[1.         1.07177346]


In [34]:
c = np.array([1,1,1])
print(a+c) #Alerta - error message comes up


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [35]:
c = np.array([1,1,1,1]).reshape(2,2)
print(a*c)
print("-"*10)
print(a.dot(c))

[[0.  0.1]
 [0.  0.1]]
----------
[0.1 0.1]


In [36]:
# Tensor dot
#https://numpy.org/doc/stable/reference/generated/numpy.tensordot.html#numpy.tensordot
a = np.arange(60.).reshape(3,4,5)
b = np.arange(24.).reshape(4,3,2)
c = np.tensordot(a,b, axes=([1,0],[0,1]))
print(c)
print(c.shape)

[[4400. 4730.]
 [4532. 4874.]
 [4664. 5018.]
 [4796. 5162.]
 [4928. 5306.]]
(5, 2)


In [37]:
# Einseum
# https://numpy.org/doc/stable/reference/generated/numpy.einsum.html

a = np.arange(25).reshape(5,5)
np.einsum("ii",a)

np.int64(60)

In [38]:
a = np.arange(1,5).reshape(2,2)
print(a)
b = np.array([0,5,6,7]).reshape(2,2)
print(b)
print("-"*10)
k = np.kron(a,b)
print(k)


[[1 2]
 [3 4]]
[[0 5]
 [6 7]]
----------
[[ 0  5  0 10]
 [ 6  7 12 14]
 [ 0 15  0 20]
 [18 21 24 28]]


In [ ]:
#Funciones sobre series


In [39]:
a = np.array(range(10))
print(np.cos(a))
print(np.exp(a))
print(np.log(a))
#alerta normal

[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458]


/var/folders/z7/r5bsb7z92m90nrt9c38l9prr0000gn/T/ipykernel_20879/928567411.py:4: RuntimeWarning: divide by zero encountered in log
  print(np.log(a))


In [40]:
print(np.sum(a))
print(np.cumsum(a))
print(np.mean(a))

print("\n",np.cumprod(a))
print(np.min(a))
print(np.argmax(a))

45
[ 0  1  3  6 10 15 21 28 36 45]
4.5

 [0 0 0 0 0 0 0 0 0 0]
0
9


In [41]:
print(np.sum(a))
print(np.cumsum(a))
print(np.mean(a))

print("\n",np.cumprod(a))
print(np.min(a))
print(np.argmax(a))


45
[ 0  1  3  6 10 15 21 28 36 45]
4.5

 [0 0 0 0 0 0 0 0 0 0]
0
9


In [42]:
a = a.reshape(2,5)
print(a)
print("-"*10)
print(np.sum(a,axis=1))
print(np.sum(a,axis=0))

[[0 1 2 3 4]
 [5 6 7 8 9]]
----------
[10 35]
[ 5  7  9 11 13]


In [ ]:
#Actividad 2. ¿Cómo calcular la distancia euclidea entre dos vectores?

In [3]:
v1 = np.arange(1,4)
v2 = np.arange(4,7)

In [11]:
print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [12]:
v1, v2


(array([1, 2, 3]), array([4, 5, 6]))

In [13]:
np.sum(v1-v2)**2


np.int64(81)

In [9]:
np.sqrt(np.sum((v1-v2)**2))

np.float64(5.196152422706632)

In [ ]:
#Actividad. ¿Y calcular la distancia de Manhattan?

In [14]:
v1-v2


array([-3, -3, -3])

In [15]:
np.sum(np.abs(v1-v2))

np.int64(9)