TTDA Primer Entrega Erika Hartai

In [4]:
import numpy as np

1. Creaci´on de arrays
(a) Crea un array a con los n´umeros del 0 al 19.
(b) Crea un array b de tama˜no 10 con n´umeros aleatorios entre 0 y 1.
(c) Crea una matriz c de 3x3 con todos sus elementos iguales a 5.

In [11]:
a = np.arange(0,20)
b = np.random.rand(10)
c = np.full((3,3), 5)
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0.73993233 0.87229555 0.66207867 0.10554863 0.01123441 0.15395039
 0.26738543 0.44501825 0.15031362 0.95368684]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


2. Indexaci´on y slicing (10 pts) Dado el array: 1 x = np.arange(10, 30)
(a) Muestra los elementos del ´ındice 3 al 8.
(b) Muestra los elementos pares del array.
(c) Cambia el valor del ´ultimo elemento a 100.

In [26]:
x = np.arange(10,30)
print(x)
print("Elementos del índice 3 al 8:", x[3:9])
print("Elementos pares de x:", x[::2])
print("Elementos pares de x:", x[x % 2 == 0])
x[-1] = 100
print(x)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
Elementos del índice 3 al 8: [13 14 15 16 17 18]
Elementos pares de x: [10 12 14 16 18 20 22 24 26 28]
Elementos pares de x: [10 12 14 16 18 20 22 24 26 28]
[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28 100]


3. Operaciones vectorizadas (15 pts)
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
(a) Calcula:
• a + b
• a * b
• b / a
(b) Eleva cada elemento de a al cuadrado usando una funci´on vectorizada.

In [33]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])


sum_ab = a + b
mult_ab = a * b
div_ab = a / b

sum_ab_2 = np.add(a, b)
producto_2 = np.multiply(a, b)
division_2 = np.divide(b, a)

print(a)
print(b)

print(sum_ab)
print(mult_ab)
print(div_ab)

print(sum_ab_2)
print(producto_2)
print(division_2)

a_quad = np.square(a)
print(a_quad)

[1 2 3 4 5]
[10 20 30 40 50]
[11 22 33 44 55]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]
[11 22 33 44 55]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[ 1  4  9 16 25]


In [ ]:
4. Estad´ısticas b´asicas
Crea un array aleatorio de 20 valores enteros entre 1 y 100:
arr = np.random.randint(1, 101, size=20)
Calcula y muestra:
(a) La media.
(b) La desviaci´on est´andar.
(c) El valor m´aximo y su posici´on (´ındice).

In [40]:
arr = np.random.randint(1, 101, size=20)
print(arr)

arr_med = np.mean(arr)
arr_std = np.std(arr)
arr_max = np.max(arr), np.argmax(arr)

print(arr_med)
print(arr_std)
print(arr_max)

[ 28  22   6  11  41  63  90  15  31  69  18 100   1  23  55  27  52   7
  95  38]
39.6
29.655353648203217
(np.int64(100), np.int64(11))


5. Manipulaci´on de matrices
(a) Crea una matriz M de tama˜no 4x4 con n´umeros del 1 al 16.
(b) Muestra:
• La primera fila.
• La ´ultima columna.
• La submatriz central de 2x2.
(c) Calcula la suma de cada fila y de cada columna.

In [62]:
M = np.arange(1,17).reshape(4,4)

print(M)
print(M[0:1])
print(M[0, -1])
print(M[1:3, 1:3])

suma_filas = np.sum(M, axis = 1)
print(suma_filas)

suma_columnas = np.sum(M, axis = 0)
print(suma_columnas)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]]
4
[[ 6  7]
 [10 11]]
[10 26 42 58]
[28 32 36 40]


In [ ]:
6. Aplicaci´on pr´actica
Sup´on que tienes un array que representa las temperaturas diarias (°C) de una
ciudad durante una semana: temps = np.array([18, 20, 22, 21, 19, 17, 16])
(a) Calcula la temperatura media semanal.
(b) Muestra qu´e d´ıas estuvieron por encima del promedio.
(c) Convierte todas las temperaturas a°F usando la f´ormula:
F= C × 9/5 + 32
d) Agrega una nueva temperatura (d´ıa 8 = 23°C) al array original.

In [73]:
temps = np.array([18, 20, 22, 21, 19, 17, 16])
print (temps)
temps_med = np.mean(temps)
print(temps_med)

convert_F_temps = temps * 9/5 + 32
print(convert_F_temps)

temps_new = np.append(temps, 23)
print(temps_new)

temps_new = np.concatenate((temps, [23]))
print(temps_new)

[18 20 22 21 19 17 16]
19.0
[64.4 68.  71.6 69.8 66.2 62.6 60.8]
[18 20 22 21 19 17 16 23]
[18 20 22 21 19 17 16 23]


7. Operaciones de conjuntos
Dadas los ficheros .csv datos 1.csv y datos 2.csv (disponibles en la p´agina de la
asignatura) que contienen respectivas arrays. Calcula y muestra:
(a) El conjunto de variables estad´ısticas b´asicas:
• Media.
• Mediana.
• Valor m´aximo y m´ınimo.
• N´umero de elementos presentes en cada fichero.
(b) La intersecci´on de los elementos de la primera fila de los dos arrays.
(c) La uni´on de los elementos de las primeras filas de los dos arrays (sin duplica-
dos).
(d) Las filas repetidas en ambos ficheros.

In [94]:
datos_1 = np.loadtxt("datos_1.csv", delimiter = ",")
datos_2 = np.loadtxt("datos_2.csv", delimiter = ",")

print(datos_1)
print("-"*53)
print(datos_2)

datos_1_mean = np.mean(datos_1)
datos_1_med = np.median(datos_1)
datos_1_max = np.max(datos_1)
datos_1_min = np.min(datos_1)
datos_1_size = datos_1.size

print(datos_1_mean)
print(datos_1_med)
print(datos_1_max)
print(datos_1_min)
print(datos_1_size)

datos_2_mean = np.mean(datos_2)
datos_2_med = np.median(datos_2)
datos_2_max = np.max(datos_2)
datos_2_min = np.min(datos_2)
datos_2_size = datos_2.size

print(datos_2_mean)
print(datos_2_med)
print(datos_2_max)
print(datos_2_min)
print(datos_2_size)

interseccion = np.intersect1d(datos_1[0], datos_2[0])
print(interseccion)

union = np.union1d(datos_1[0], datos_2[0])
print(union)

repetidas = np.array([fila for fila in datos_1 if (fila == datos_2).all(axis=1).any()])
print(np.array(repetidas))



[[ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]
 [ 52.  14.  90.   2.   7.  79.  57.   1.  43.  27.]
 [ 36.  31.  46.  79.  25.  61. 100.  63.  36.  24.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]
 [ 60.  90.  67.  66.  34.  71.  93.  20.  77.  51.]
 [ 24.  62.  72.  17.  78.  93.  52.  24.  86.  10.]]
-----------------------------------------------------
[[ 38.   5.   6.  57.  67.  52.  77.  99.  80.  74.]
 [ 49.  44.  20.  97.   3.  82.  46.  81. 100.  47.]
 [ 83.  59.  33.  95.  94.  76.  91.  33.  55.  62.]
 [ 34.  25.  85.  61.  65.  73.  59.  22.  45.  90.]
 [ 14.  60.  46.  85.  52.  93.  38.  89.  79.  10.]
 [ 42.  16.   8.  95.  59.  57.  91.  75.   5.  45.]]
53.233333333333334
57.0
100.0
1.0
60
57.05
59.0
100.0
3.0
60
[ 5. 57.]
[ 5.  6.  8. 16. 38. 42. 45. 52. 57. 59. 67. 74. 75. 77. 80. 91. 95. 99.]
[[42. 16.  8. 95. 59. 57. 91. 75.  5. 45.]
 [83. 59. 33. 95. 94. 76. 91. 33. 55. 62.]]
